### ISSUE TITLE
Failed to connect to localhost port 9200: Connection refused

### ISSUE THREAD

**Issue by willystadnick** [waldemarnt/elasticsearch-php-example#2]
$ php Example.php 

```
PHP Fatal error:  Uncaught exception 'Elasticsearch\Common\Exceptions\Curl\CouldNotConnectToHost' with message 'Failed to connect to localhost port 9200: Connection refused' in /home/willy/Projects/wsn/tests/elasticsearch-php-example/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/AbstractConnection.php:323
Stack trace:
#0 /home/willy/Projects/wsn/tests/elasticsearch-php-example/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(319): Elasticsearch\Connections\AbstractConnection->throwCurlException(7, 'Failed to conne...')
#1 /home/willy/Projects/wsn/tests/elasticsearch-php-example/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(206): Elasticsearch\Connections\GuzzleConnection->processCurlError(Object(Guzzle\Http\Exception\CurlException))
#2 /home/willy/Projects/wsn/tests/elasticsearch-php-example/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(104): Elasticsearch\Connections\GuzzleConnection->sendReq in /home/willy/Projects/wsn/tests/elasticsearch-php-example/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/AbstractConnection.php on line 323
```

$ php -v

```
PHP 5.6.11-1ubuntu3.4 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

**Comment by willystadnick** [comment]
Sorry. I've just reinstalled elasticsearch service and everything worked fine.
